---
title: "Spatial Maps by Temperature"
always_allow_html: true
output:
   html_document:
---

```{r packages, results='hide',echo=FALSE}
# Installation and Loading of Packages Required for the project

packages <- c("rgdal","raster","tmap","maptools","tidyverse","broom","knitr",
              "kableExtra","RColorBrewer","plotly","htmlwidgets","weathermetrics",
              "glue")

if(sum(as.numeric(!packages %in% installed.packages())) != 0){
  instalador <- packages[!packages %in% installed.packages()]
  for(i in 1:length(instalador)) {
    install.packages(instalador, dependencies = T)
    break()}
  sapply(packages, require, character = T) 
} else {
  sapply(packages, require, character = T) 
}
```

```{r setup, include=FALSE, echo=TRUE}
library(reticulate)
use_python("C:/Users/tamer/AppData/Local/Programs/Python/Python37/python.exe")
```

```{r}
# Sign up for free on the site:https://openweathermap.org/api and enter your api in the code below 
```

```{python requests, results="hide"}
import csv
import requests

api_key = 'bc656b9222f7f091184dccaa5d217f50'

# Clear the csv for new consulting
f = open("temp_pennsylvania.csv", "w")
f.truncate()
f.close()

header_added = False
with open("data_long_lat.csv", 'r', newline="",encoding='latin-1') as file:
  reader = csv.reader(file, delimiter=';')
  for row in reader:
    latlongwheater = f'http://api.openweathermap.org/data/2.5/weather?lat={row[1]}&lon={row[2]}&units=metric&appid={api_key}'
    source = requests.get(latlongwheater)
    temp_local = source.json()['main']['temp']
    
    with open("./temp_pennsylvania.csv", "a", newline="",encoding='latin-1') as file2:
      writer = csv.writer(file2, delimiter=',')
      if not header_added:
        writer.writerow(['NM_MUNICIP','TEMP'])
        header_added = True
      writer.writerow([row[0], temp_local])

```

```{r shapefiles,results='hide'}
# 1. LOADING AND MERGING THE DATA

# Loading shapefile from EUA-Pennsylvania -------------------------------------------------
shp_pennsylvania <- readOGR(dsn = "PaCounty", layer = "PaCounty2022_01")

#To access a shapefile database, we must use the @ operator:
shp_pennsylvania@data %>% 
  kable() %>%
  kable_styling(bootstrap_options = "striped", 
                full_width = TRUE, 
                font_size = 12)


#Loading the previously constructed temperature table
tabel_temp<- read.csv(file = 'temp_pennsylvania.csv')

#Convert from Celsius to Fahrenheit
tabel_temp$TEMP <- celsius.to.fahrenheit(T.celsius =as.numeric(tabel_temp$TEMP),round = 2 )

# Capitalize the NM_MUNICIP column of the table_file to be ready to merge with the shapefile
tabel_temp$NM_MUNICIP = toupper(tabel_temp$NM_MUNICIP)

# Merge the shapefile with the table_temp
shp_dados_pennsylvania <- merge(x =shp_pennsylvania,
                               y = tabel_temp,
                               by.x = "COUNTY_NAM",
                               by.y = "NM_MUNICIP")


# 2. VISUALIZATION OF SPATIAL DATA

# Using ggplot2:

# Step 1: Transform the shapefile into a data frame object and then
# import data not already in the shapefile into the new data frame object.

shp_dados_pennsylvania_df <- tidy(shp_dados_pennsylvania, region = "COUNTY_NAM") %>% 
  rename(COUNTY_NAM = id) %>% 
  left_join(shp_dados_pennsylvania@data,
            by = "COUNTY_NAM")


#Step 2: The Plot.

timestamp <- paste(format(Sys.time(), "%m_%d_%Y"),format(Sys.time(), "%H_%M_%S"))

plot_pennsylvania <- shp_dados_pennsylvania_df %>% 
  ggplot(aes(text = paste("Temp ºF: ", plot_pennsylvania$data$TEMP,
                          "<br>Local: ", plot_pennsylvania$data$COUNTY_NAM,
                          "<br>Area (Sq.Mi): ", plot_pennsylvania$data$AREA_SQ_MI)))+
  geom_polygon(aes(x = long, y = lat, group = group, fill = TEMP),
               color = "black")+
  labs(x = "Longitude",
       y = "Latitude",
       fill="Temp ºF",
       title=paste('Pennsylvania Counties',
                   paste(format(Sys.time(), "%m/%d/%Y"),format(Sys.time(), "%H:%M:%S"))),
       color = "temp") +
  scale_fill_viridis_c() +
  theme_bw()

plot_pennsylvania

```

```{r}
#Save the images as png file
name_file <-"./Assets/png_files/{timestamp}.png"
ggsave(glue(name_file),plot=plot_pennsylvania, width = 1920/72, height = 1080/72, dpi = 72)


#Save the image in html file which allows you the plotly experience
image_plotly<-ggplotly(plot_pennsylvania,tooltip = "text")
image_plotly

htmlwidgets::saveWidget(image_plotly, file = glue("{timestamp}.html"), selfcontained=TRUE) 

# Export the file as unique html file from the main folder to a specific folder
file.rename(glue("{timestamp}.html"), glue("./Assets/html_files/{timestamp}.html"))

```
